[package]
name = "cooking_recipes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
persistent_config = { path = "../../persistent_config", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
